name: weather_app
description: A Flutter app to display weather information.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dotted_line: ^3.2.2
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.4.4
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
      - assets/weather_data.json
      - assets/cloudy.png
      - assets/rainy.png
      - assets/Vector.png
      - assets/Line_one.png
      - assets/line_two.png
